PluggedInPortal/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PluggedInDataAccess;
using System.Net;

namespace PluggedInPortal.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        PluggedInEntities db = new PluggedInEntities();
        // GET: Admin
        public ActionResult Index()
        {
            Models.Metrics metrics = new Models.Metrics
            {
                TotalUsersCount = db.AspNetUsers.Count() - 1,
                ApplicationsRejectedCount = db.Agencies.Where(a => a.ApplicationStatus == "REJECTED").Count(),
                PendingApprovalCount = db.Agencies.Where(a => a.ApplicationStatus == "PENDING REVIEW").Count(),
                TotalEventsCount = db.Events.Count(),
                UpcomingEventCount = db.Events.Where(e => e.StartDate > DateTime.Now).Count(),
                BannerCount = db.Banners.Count()
            };
            return View(metrics);
        }


        public ActionResult ViewPendingApplications()
        {
            IEnumerable<Agency> allAgenciesPendingReview = new List<Agency>();
            allAgenciesPendingReview = db.Agencies.Where(a => a.ApplicationStatus == "PENDING REVIEW").ToList();
            return View(allAgenciesPendingReview);

        }

        public ActionResult ViewRejectedApplications()
        {
            IEnumerable<Agency> rejectedAgencyApplications = new List<Agency>();
            rejectedAgencyApplications = db.Agencies.Where(a => a.ApplicationStatus == "REJECTED").ToList();
            return View(rejectedAgencyApplications);
        }

        public ActionResult ViewAllEvents()
        {
            IEnumerable<Event> events = new List<Event>();
            events = db.Events.OrderByDescending(e => e.StartDate).ToList();
            return View(events);
        }

        public ActionResult ViewUsers()
        {
            IEnumerable<AspNetUser> users = new List<AspNetUser>();
            users = db.AspNetUsers.Where(u=> u.Email != "administrator@youthemployment.portal").ToList();
            if(TempData["LastAction"] != null)
            {
                ViewBag.LastAction = TempData["LastAction"].ToString();
            }
            return View(users);
        }

        public ActionResult DisableUser(string id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser user = db.AspNetUsers.Find(id);
            if(user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            //db.Entry(user).State = System.Data.Entity.EntityState.Modified;
            //user.LockoutEndDateUtc = DateTime.Now.AddDays(7);
            //db.SaveChanges();
            return View(user);
        }

        [HttpPost]
        public ActionResult DisableUser(AspNetUser user, DateTime EndDate)
        {
            AspNetUser u = db.AspNetUsers.Find(user.Id);
            if (u == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            db.Entry(u).State = System.Data.Entity.EntityState.Modified;
            u.LockoutEndDateUtc = EndDate;
            db.SaveChanges();
            TempData["LastAction"] = u.Email + " has been locked";

            return RedirectToAction("ViewUsers");
        }

        public ActionResult UnlockUser(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            AspNetUser user = db.AspNetUsers.Find(id);
            if (user == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            db.Entry(user).State = System.Data.Entity.EntityState.Modified;
            user.LockoutEndDateUtc = DateTime.Now;
            db.SaveChanges();
            TempData["LastAction"] = user.Email + " is now unlocked.";
            return RedirectToAction("ViewUsers");
        }

        public ActionResult ViewApplication(int? AgencyId)
        {
            if (AgencyId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agency agency = db.Agencies.Find(AgencyId);
            if (agency == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            return View(agency);

        }

        public ActionResult ApproveApplication(int? AgencyId)
        {
            if(AgencyId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agency agency = db.Agencies.Find(AgencyId);
            if (agency == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);


            db.Entry(agency).State = System.Data.Entity.EntityState.Modified;
            agency.ApplicationStatus = "APPROVED";
            db.SaveChanges();

            return RedirectToAction("ViewPendingApplications");


        }

        public ActionResult RejectApplication(int? AgencyId)
        {
            if (AgencyId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agency agency = db.Agencies.Find(AgencyId);
            if (agency == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);


            db.Entry(agency).State = System.Data.Entity.EntityState.Modified;
            agency.ApplicationStatus = "REJECTED";
            db.SaveChanges();

            return RedirectToAction("ViewPendingApplications");


        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PluggedInPortal/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PluggedInDataAccess;
using System.Device;
using System.Device.Location;

namespace PluggedInPortal.Controllers
{
    public class EventController : Controller
    {
        PluggedInDataAccess.PluggedInEntities db = new PluggedInDataAccess.PluggedInEntities();
        // GET: Event
        public ActionResult Index()
        {
            List<Event> events = new List<Event>();
            events = db.Events.ToList();
            IEnumerable<SelectListItem> items = db.Resources.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            });

            ViewBag.NumberOfResults = "Results";
            ViewBag.ResourceList = items;

            return View(events);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult SearchEvents(int? ResourceList, string userLat, string userLong)
        {
            IEnumerable<SelectListItem> items = db.Resources.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            });

            List<Event> events = new List<Event>();
            events = db.Events.ToList();

            

            List<Event> newList = new List<Event>();

            Resource r = new Resource();
            r = db.Resources.Find(ResourceList);

            foreach (Event a in events)
            {
                if (a.ResourceId == r.Id && (a.Longtitude != null && a.Latitude != null))
                {
                    if(userLat != "" && userLong != "")
                    {
                        var sCoord = new GeoCoordinate(Convert.ToDouble(userLat), Convert.ToDouble(userLong));
                        var eCoord = new GeoCoordinate(Convert.ToDouble(a.Latitude), Convert.ToDouble(a.Longtitude));
                        a.Distance = Math.Round((sCoord.GetDistanceTo(eCoord) / 1000), 2);
                    }
                    newList.Add(a);
                }
            }

            List<Event> sortedList = new List<Event>();

            if (userLat != "" && userLong != "")
            {
                sortedList = newList.OrderBy(o => o.Distance).ToList();
            }
            else
            {
                sortedList = newList;
            }  

            if (sortedList.Count() > 0)
            {
                ViewBag.NumberOfResults = "Results";
                ViewBag.ResourceList = items;

                return View("Index", sortedList);
            }
            else
            {
                ViewBag.NumberOfResults = "No Results Found";
                ViewBag.ResourceList = items;

                return View("Index");
            }


        }
    }
}

PluggedInPortal/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;
@{
    var userId = User.Identity.GetUserId();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <title>@ViewBag.Title - Youth Employment Portal</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>

    </style>
</head>
<body class="animated fadeIn">
    <div class="navbar navbar-inverse navbar-fixed-top" id="top-navbar" style="background:#3c3e42;box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a style="color:white; font-size: 110%;" href="@Url.Action("HomePage", "Home", new { area = "", id = userId })" class="navbar-brand">
                    <img src="~/Assets/logo.png" title="yep-logo" alt="" />Youth Employment Portal
                </a>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("All Events", "Index", "Event", null, new { @class = "white-text" })</li>
                    @if (Request.IsAuthenticated)
                    {

                        @*<li>@Html.ActionLink("Home", "Index", "Home", routeValues: new { id = userId }, htmlAttributes: new { @class = "white-text" })</li>
            <li>@Html.ActionLink("About", "About", "Home", htmlAttributes: new { @class = "white-text" })</li>
            <li>@Html.ActionLink("Contact", "Contact", "Home", htmlAttributes: new { @class = "white-text" })</li>*@
                        if (User.IsInRole("Administrator"))
                        {
                            <li>@Html.ActionLink("Banners", "Index", "Banners", routeValues: null, htmlAttributes: new { @class = "white-text" })</li>
                            <li>@Html.ActionLink("Review Applications", "ViewPendingApplications", "Admin", routeValues: null, htmlAttributes: new { @class = "white-text" })</li>
                        }

                        if (User.IsInRole("Agency"))
                        {
                            PluggedInDataAccess.PluggedInEntities db = new PluggedInDataAccess.PluggedInEntities();
                            var a = db.AspNetUsers.Find(userId).Agency;

                            <li>@Html.ActionLink("My Events", "ManageEvent", "Home", routeValues: new { agencyId = a.Id }, htmlAttributes: new { @class = "white-text" })</li>
                            <li>@Html.ActionLink("Your Agency Application", "CreateAgencyApplication", "Home", routeValues: new { id = userId }, htmlAttributes: new { @class = "white-text" })</li>
                        }
                        if (User.IsInRole("Resident") || User.IsInRole("Agency"))
                        {
                            <li>@Html.ActionLink("My Home", "Index", "Home", null, htmlAttributes: new { @class = "white-text" })</li>
                        }
                        else if (User.IsInRole("Administrator"))
                        {
                            <li>@Html.ActionLink("Dashboard", "Index", "Home", null, htmlAttributes: new { @class = "white-text" })</li>
                        }

                    }
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

    </div>
    <footer class="navbar-inverse" style="background:#3c3e42">


        <div class="navbar navbar-inverse" style="background:#3c3e42">
            <div class="container">
                <div class="navbar-header">
                    @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>*@
                    <a href="@Url.Action("HomePage", "Home", new { area = "", id = userId })">
                        <h3 style="font-size: 110%;"><img src="~/Assets/logo.png" title="yep-logo" alt="" />Youth Employment Portal</h3>
                    </a>

                </div>

                <div class="navbar-collapse collapse">
                    <br />
                    <ul class="nav navbar-nav navbar-right">
                        <li><strong>About Us</strong></li>
                        <li>&nbsp;&nbsp;&nbsp;&nbsp;<strong>Contact Us</strong></li>
                    </ul>
                </div>
                <p style="font-size: 100%;">
                    Mission statement goes here or whatever information or details. <br />
                    More Mission statement goes here or whatever information or details.
                </p>
                <br />
                <i class="fab fa-twitter fa-2x"></i>
                <i class="fab fa-instagram fa-2x"></i>
            </div>
        </div>


    </footer>
    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>