PluggedInPortal/Controllers/BannersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PluggedInDataAccess;

namespace PluggedInPortal.Controllers
{
    [Authorize(Roles ="Administrator")]
    public class BannersController : Controller
    {
        private PluggedInEntities db = new PluggedInEntities();

        // GET: Banners
        public ActionResult Index()
        {
            return View(db.Banners.ToList());
        }

        // GET: Banners/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Banner banner = db.Banners.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        // GET: Banners/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Banners/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,StartDate,EndDate,UploadedBy,BannerImage,Name")] Banner banner, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if(image != null)
                {
                    banner.BannerImage = new byte[image.ContentLength];
                    image.InputStream.Read(banner.BannerImage, 0, image.ContentLength);
                }
                db.Banners.Add(banner);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(banner);
        }

        // GET: Banners/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Banner banner = db.Banners.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        // POST: Banners/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StartDate,EndDate,UploadedBy,BannerImage,Name")]Banner banner, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    banner.BannerImage = new byte[image.ContentLength];
                    image.InputStream.Read(banner.BannerImage, 0, image.ContentLength);
                }
                else
                {

                }
                db.Entry(banner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(banner);
        }

        // GET: Banners/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Banner banner = db.Banners.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        // POST: Banners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Banner banner = db.Banners.Find(id);
            db.Banners.Remove(banner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PluggedInPortal/Views/Banners/Create.cshtml
@model PluggedInDataAccess.Banner
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "Banners", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br />
        <br />
        <h3>Upload Banner</h3>
        <hr />
        <br />

        <div style="width: 100%;">
            <div style="float: left; width: 40%;">
                <div class="form-group">
                    <div class="col-md-10">
                        <img src="" height="100" style="width:100%; float:left;" id="image-preview" />
                        @*@Html.EditorFor(model => model.BannerImage, new { htmlAttributes = new { @class = "form-control" } })*@
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <input type="file" id="image" name="image" onchange="preview_image(event)" style="float:left; margin-left: 110px;" />
                        @Html.ValidationMessageFor(model => model.BannerImage, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div style="float: left; width: 45%;">

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="container">
                    <div class='col-md-10'>
                        <label for="eventEndDate" style="text-align: center; clear: both; float: left; margin-right: 12%; left:5%; position: relative;">Start Date</label>
                        <div class="form-group">
                            <div class='input-group date' id='startDate'>
                                <input type='text' class="form-control" name="StartDate" id="StartDate" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <br />
                    <br />
                    

                    <div class='col-md-10'>
                        <label for="eventEndDate" style="text-align: center; clear: both; float: left; margin-right: 14%; left:5%; position: relative;">End Date</label>
                        <div class="form-group">
                            <div class='input-group date' id='endDate'>
                                <input type='text' class="form-control" name="EndDate" id="EndDate" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2" for="UploadedBy">By</label>
                    @*@Html.LabelFor(model => model.UploadedBy, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.UploadedBy, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @value=User.Identity.Name } })*@
                        <input type="text" readonly="readonly" value="@User.Identity.Name" class="form-control" id="UploadedBy" name="UploadedBy" />
                        @*@Html.ValidationMessageFor(model => model.UploadedBy, "", new { @class = "text-danger" })*@
                    </div>
                </div>
            </div>

            <div style="float: left; width: 15%;">
                <div class="form-group">

                    <input type="submit" value="Create" class="btn yep-btn" />

                </div>
            </div>
        </div>
    </div>
}

<!-- Latest compiled and minified CSS --> <!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>


    

<script>

    $(document).ready(function () {
        $(function () {
            $('#startDate').datetimepicker();
            $('#endDate').datetimepicker({
                useCurrent: true
            });
            $("#startDate").on("dp.change", function (e) {
                $('#endDate').data("DateTimePicker").minDate(e.date);
            });
            $("#endDate").on("dp.change", function (e) {
                $('#startDate').data("DateTimePicker").maxDate(e.date);
            });
        });
    });


    function preview_image(event) {
        var reader = new FileReader();
        reader.onload = function () {
            var output = document.getElementById('image-preview');
            output.src = reader.result;
        }   
        reader.readAsDataURL(event.target.files[0]);
    }
</script>

PluggedInPortal/Views/Banners/Delete.cshtml
@model PluggedInDataAccess.Banner

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Banner</h4>
    <hr />
    <div class="form-horizontal">

        <div style="width: 100%;">
            <div style="float: left; width: 40%;">
                <div class="form-group">
                    @*@Html.LabelFor(model => model.BannerImage, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <div class="col-md-10">
                        @{
                            if (Model.BannerImage != null)
                            {
                                string imageBase64 = Convert.ToBase64String(Model.BannerImage);
                                string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                                <img src="@imageSrc" height="100" style="width:100%" id="image-preview" />
                            }
                        }
                        @*<input type="file" id="image" name="image" onchange="preview_image(event)" />*@
                        @*@Html.EditorFor(model => model.BannerImage, new { htmlAttributes = new { @class = "form-control" } })*@
                        @Html.HiddenFor(model => model.BannerImage)
                        @Html.ValidationMessageFor(model => model.BannerImage, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div style="float: left; width: 45%;">

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2" for="UploadedBy">By</label>
                    @*@Html.LabelFor(model => model.UploadedBy, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.UploadedBy, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @value=User.Identity.Name } })*@
                        <input type="text" readonly="readonly" value="@User.Identity.Name" class="form-control" id="UploadedBy" name="UploadedBy" />
                        @*@Html.ValidationMessageFor(model => model.UploadedBy, "", new { @class = "text-danger" })*@
                    </div>
                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PluggedInPortal/Views/Banners/Details.cshtml
@model PluggedInDataAccess.Banner

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div class="form-horizontal">

    <div style="width: 100%;">
        <div style="float: left; width: 40%;">
            <div class="form-group">
                @*@Html.LabelFor(model => model.BannerImage, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @{
                        if (Model.BannerImage != null)
                        {
                            string imageBase64 = Convert.ToBase64String(Model.BannerImage);
                            string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                            <img src="@imageSrc" height="100" style="width:100%" id="image-preview" />
                        }
                    }
                    @*<input type="file" id="image" name="image" onchange="preview_image(event)" />*@
                    @*@Html.EditorFor(model => model.BannerImage, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.HiddenFor(model => model.BannerImage)
                    @Html.ValidationMessageFor(model => model.BannerImage, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div style="float: left; width: 45%;">

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.UploadedBy, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <label class="control-label col-md-2" for="UploadedBy">By</label>
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.UploadedBy, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @value=User.Identity.Name } })*@
                    <input type="text" readonly="readonly" value="@User.Identity.Name" class="form-control" id="UploadedBy" name="UploadedBy" />
                    @*@Html.ValidationMessageFor(model => model.UploadedBy, "", new { @class = "text-danger" })*@
                </div>
            </div>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PluggedInPortal/Views/Banners/Edit.cshtml
@model PluggedInDataAccess.Banner
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "Banners", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br />
        <br />
        <h3>Edit Banner</h3>
        <hr />
        <br />

        <div style="width: 100%;">
            <div style="float: left; width: 40%;">
                <div class="form-group">
                    @*@Html.LabelFor(model => model.BannerImage, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <div class="col-md-10">
                        @{
                            if (Model.BannerImage != null)
                            {
                                string imageBase64 = Convert.ToBase64String(Model.BannerImage);
                                string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                                <img src="@imageSrc" height="100" style="width:100%" id="image-preview" />
                            }
                        }
                        <input type="file" id="image" name="image" onchange="preview_image(event)" />
                        @*@Html.EditorFor(model => model.BannerImage, new { htmlAttributes = new { @class = "form-control" } })*@
                        @Html.HiddenFor(model => model.BannerImage)
                        @Html.ValidationMessageFor(model => model.BannerImage, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div style="float: left; width: 45%;">

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @*<div class="form-group">
                        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                <div class="container">
                    <div class='col-md-10'>
                        <label for="eventEndDate" style="text-align: center; clear: both; float: left; margin-right: 12%; left:5%; position: relative;">Start Date</label>
                        <div class="form-group">
                            <div class='input-group date' id='startDate'>
                                <input type='datetime' class="form-control" name="StartDate" id="StartDate" value="@Model.StartDate"/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <br />
                    <br />


                    <div class='col-md-10'>
                        <label for="eventEndDate" style="text-align: center; clear: both; float: left; margin-right: 14%; left:5%; position: relative;">End Date</label>
                        <div class="form-group">
                            <div class='input-group date' id='endDate'>
                                <input type='datetime' class="form-control" name="EndDate" id="EndDate" value="@Model.EndDate"/>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2" for="UploadedBy">By</label>
                    @*@Html.LabelFor(model => model.UploadedBy, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.UploadedBy, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @value=User.Identity.Name } })*@
                        <input type="text" readonly="readonly" value="@User.Identity.Name" class="form-control" id="UploadedBy" name="UploadedBy" />
                        @*@Html.ValidationMessageFor(model => model.UploadedBy, "", new { @class = "text-danger" })*@
                    </div>
                </div>
            </div>

            <div style="float: left; width: 15%;">
                <div class="form-group">

                    <input type="submit" value="Update" class="btn yep-btn" />

                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<!-- Latest compiled and minified CSS --> <!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>



<script>


    $(document).ready(function () {
        $(function () {
            $('#startDate').datetimepicker({
                date: new Date("@Model.StartDate")
            });
            $('#endDate').datetimepicker({
                date: new Date("@Model.EndDate"),
                useCurrent: true
            });

           
           
            $("#startDate").on("dp.change", function (e) {
                $('#endDate').data("DateTimePicker").minDate(e.date);
            });
            $("#endDate").on("dp.change", function (e) {
                $('#startDate').data("DateTimePicker").maxDate(e.date);
            });
        });

         

    });

    function preview_image(event) {
        var reader = new FileReader();
        reader.onload = function () {
            var output = document.getElementById('image-preview');
            output.src = reader.result;
        }
        reader.readAsDataURL(event.target.files[0]);
    }
</script>

PluggedInPortal/Views/Banners/Index.cshtml
@model IEnumerable<PluggedInDataAccess.Banner>

@{
    ViewBag.Title = "Index";
}
<br />

<link href="~/Content/bootstrap-table.css" rel="stylesheet" />
<div>
    @*@Html.Partial("Create", new PluggedInDataAccess.Banner());*@
</div>
<br />
<br/>
<p>
    @Html.ActionLink("Create New", "Create", routeValues: null, htmlAttributes: new { @class = "yep-btn" })
</p>

<table class="table table-bordered table-hover" id="bannerTable" cellSpacing="0" data-show-toggle="true"
       data-show-columns="true" data-search="true" data-pagination="true" data-filter-control="true">
    <thead>
        <tr>
            <th></th>
            <th data-field="Name">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th data-field="StartDate" data-sortable="true">
                Start Date
            </th>
            <th data-field="End Date" data-sortable="true">
                End Date
            </th>
            <th data-field="By" data-sortable="true">
                By
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.BannerImage)
                </th>*@

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @{
                        if (item.BannerImage != null)
                        {
                            string imageBase64 = Convert.ToBase64String(item.BannerImage);
                            string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                            <img src="@imageSrc" width="100" height="100" />
                        }
                    }
                    @*@Html.DisplayFor(modelItem => item.BannerImage)*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>



                <td>
                    @Html.DisplayFor(modelItem => item.UploadedBy)
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="~/Scripts/bootstrap-table.js"></script>
<script src="~/Scripts/bootstrap-table-filter-control.js"></script>
<script>
    $('#bannerTable').bootstrapTable({
    });
</script>